export const CARD_GAME = { POKEMON: "POKEMON" } as const
export type CardGame = (typeof CARD_GAME)[keyof typeof CARD_GAME]

export const CARD_LANGUAGE = { EN: "EN", JA: "JA", ZH: "ZH" } as const
export type CardLanguage = (typeof CARD_LANGUAGE)[keyof typeof CARD_LANGUAGE]

export const RECORD_ORIGIN = {
  MANUAL: "MANUAL",
  TCGDEX: "TCGDEX",
  PULSE: "PULSE",
  OTHER: "OTHER",
} as const
export type RecordOrigin = (typeof RECORD_ORIGIN)[keyof typeof RECORD_ORIGIN]

export const CARD_CONDITION = {
  NEAR_MINT: "NEAR_MINT",
  LIGHTLY_PLAYED: "LIGHTLY_PLAYED",
  MODERATELY_PLAYED: "MODERATELY_PLAYED",
  HEAVILY_PLAYED: "HEAVILY_PLAYED",
  DAMAGED: "DAMAGED",
} as const
export type CardCondition = (typeof CARD_CONDITION)[keyof typeof CARD_CONDITION]

export const CONDITION_SOURCE = { EXPLICIT: "EXPLICIT", DEFAULTED: "DEFAULTED" } as const
export type ConditionSource = (typeof CONDITION_SOURCE)[keyof typeof CONDITION_SOURCE]

export const CARD_FINISH = {
  NORMAL: "NORMAL",
  HOLO: "HOLO",
  REVERSE_HOLO: "REVERSE_HOLO",
  OTHER: "OTHER",
} as const
export type CardFinish = (typeof CARD_FINISH)[keyof typeof CARD_FINISH]

export const SPECIAL_TREATMENT = {
  NONE: "NONE",
  ENERGY_REVERSE: "ENERGY_REVERSE",
  POKE_BALL_REVERSE: "POKE_BALL_REVERSE",
  MASTER_BALL_REVERSE: "MASTER_BALL_REVERSE",
  LOVE_BALL_REVERSE: "LOVE_BALL_REVERSE",
  QUICK_BALL_REVERSE: "QUICK_BALL_REVERSE",
  FRIEND_BALL_REVERSE: "FRIEND_BALL_REVERSE",
  DUSK_BALL_REVERSE: "DUSK_BALL_REVERSE",
  ROCKET_REVERSE: "ROCKET_REVERSE",
  POKE_BALL: "POKE_BALL",
  MASTER_BALL: "MASTER_BALL",
  STARLIGHT_HOLO: "STARLIGHT_HOLO",
  COSMOS_HOLO: "COSMOS_HOLO",
  GALAXY_HOLO: "GALAXY_HOLO",
  CRACKED_ICE: "CRACKED_ICE",
  STAMPED: "STAMPED",
  PRERELEASE_STAMPED: "PRERELEASE_STAMPED",
  PROMOTIONAL_STAMPED: "PROMOTIONAL_STAMPED",
  TEXTURED: "TEXTURED",
  ETCHED: "ETCHED",
  OTHER: "OTHER",
} as const
export type SpecialTreatment = (typeof SPECIAL_TREATMENT)[keyof typeof SPECIAL_TREATMENT]

export const RARITY = {
  ACE_SPEC: "ACE_SPEC",
  BLACK_WHITE_RARE: "BLACK_WHITE_RARE",
  COMMON: "COMMON",
  DOUBLE_RARE: "DOUBLE_RARE",
  HYPER_RARE: "HYPER_RARE",
  ILLUSTRATION_RARE: "ILLUSTRATION_RARE",
  MEGA_ATTACK_RARE: "MEGA_ATTACK_RARE",
  MEGA_HYPER_RARE: "MEGA_HYPER_RARE",
  NO_RARITY: "NO_RARITY",
  PROMO: "PROMO",
  SHINY_ULTRA_RARE: "SHINY_ULTRA_RARE",
  ULTRA_RARE_SINGLE: "ULTRA_RARE_SINGLE",
  ULTRA_RARE: "ULTRA_RARE",
  UNCOMMON: "UNCOMMON",
} as const
export type Rarity = (typeof RARITY)[keyof typeof RARITY]

export const RARITY_ICON_KEY = {
  ACE_SPEC: "ace-spec",
  BLACK_WHITE_RARE: "black-white-rare",
  COMMON: "common",
  DOUBLE_RARE: "double-rare",
  HYPER_RARE: "hyper-rare",
  ILLUSTRATION_RARE: "illustration-rare",
  MEGA_ATTACK_RARE: "mega-attack-rare",
  MEGA_HYPER_RARE: "mega-hyper-rare",
  NO_RARITY: "no-rarity",
  PROMO: "promo",
  SHINY_ULTRA_RARE: "shiny-ultra-rare",
  ULTRA_RARE_SINGLE: "ultra-rare-single",
  ULTRA_RARE: "ultra-rare",
  UNCOMMON: "uncommon",
} as const
export type RarityIconKey = (typeof RARITY_ICON_KEY)[keyof typeof RARITY_ICON_KEY]

export const EXTERNAL_PROVIDER = {
  TCGDEX: "TCGDEX",
  PULSE: "PULSE",
  EBAY: "EBAY",
  OTHER: "OTHER",
} as const
export type ExternalProvider = (typeof EXTERNAL_PROVIDER)[keyof typeof EXTERNAL_PROVIDER]

export const EXTERNAL_REFERENCE_PROVENANCE = {
  AUTOMATIC: "AUTOMATIC",
  TRUSTED_MANUAL: "TRUSTED_MANUAL",
} as const
export type ExternalReferenceProvenance = (typeof EXTERNAL_REFERENCE_PROVENANCE)[keyof typeof EXTERNAL_REFERENCE_PROVENANCE]

export const AUDIT_ENTITY_TYPE = {
  TRADING_CARD: "TRADING_CARD",
  TRADING_CARD_VARIANT: "TRADING_CARD_VARIANT",
  EXTERNAL_CARD_REFERENCE: "EXTERNAL_CARD_REFERENCE",
  ENRICHMENT_PROPOSAL: "ENRICHMENT_PROPOSAL",
  CARD_IMAGE: "CARD_IMAGE",
} as const

export const AUDIT_ACTION = {
  CANONICAL_IDENTITY_CHANGED: "CANONICAL_IDENTITY_CHANGED",
  CONDITION_CHANGED: "CONDITION_CHANGED",
  FINISH_CHANGED: "FINISH_CHANGED",
  SPECIAL_TREATMENT_CHANGED: "SPECIAL_TREATMENT_CHANGED",
  PRICE_LOCKED: "PRICE_LOCKED",
  PRICE_UNLOCKED: "PRICE_UNLOCKED",
  EXTERNAL_REFERENCE_ADDED: "EXTERNAL_REFERENCE_ADDED",
  EXTERNAL_REFERENCE_CHANGED: "EXTERNAL_REFERENCE_CHANGED",
  EXTERNAL_REFERENCE_REMOVED: "EXTERNAL_REFERENCE_REMOVED",
  TCGDEX_ENRICHMENT_RECORDED: "TCGDEX_ENRICHMENT_RECORDED",
  TCGDEX_ENRICHMENT_SUPERSEDED: "TCGDEX_ENRICHMENT_SUPERSEDED",
  TCGDEX_ENRICHMENT_APPROVED: "TCGDEX_ENRICHMENT_APPROVED",
  TCGDEX_ENRICHMENT_REJECTED: "TCGDEX_ENRICHMENT_REJECTED",
  TCGDEX_ENRICHMENT_APPLIED: "TCGDEX_ENRICHMENT_APPLIED",
  TCGDEX_MANUAL_REFERENCE_RECORDED: "TCGDEX_MANUAL_REFERENCE_RECORDED",
  IMAGE_UPLOAD_REQUESTED: "IMAGE_UPLOAD_REQUESTED",
  IMAGE_UPLOAD_CONFIRMED: "IMAGE_UPLOAD_CONFIRMED",
  IMAGE_UPLOAD_REJECTED: "IMAGE_UPLOAD_REJECTED",
  IMAGE_UPLOAD_EXPIRED: "IMAGE_UPLOAD_EXPIRED",
  IMAGE_DUPLICATE_DETECTED: "IMAGE_DUPLICATE_DETECTED",
  IMAGE_REORDERED: "IMAGE_REORDERED",
  IMAGE_FOCAL_CHANGED: "IMAGE_FOCAL_CHANGED",
  IMAGE_ARCHIVED: "IMAGE_ARCHIVED",
  IMAGE_RESTORED: "IMAGE_RESTORED",
} as const

/**
 * Stage 4B.1 lifecycle. PENDING images have no confirmed bytes yet;
 * READY images are active and reusable; DUPLICATE/REJECTED/EXPIRED are
 * terminal non-active outcomes of the (not yet built) confirmation step;
 * ARCHIVED is the only lifecycle exit from READY and is always reversible.
 */
export const IMAGE_STATUS = {
  PENDING: "PENDING",
  READY: "READY",
  DUPLICATE: "DUPLICATE",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  ARCHIVED: "ARCHIVED",
} as const
export type ImageStatus = (typeof IMAGE_STATUS)[keyof typeof IMAGE_STATUS]

export const SUPPORTED_IMAGE_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"] as const
export type SupportedImageMimeType = (typeof SUPPORTED_IMAGE_MIME_TYPES)[number]
