export { TcgDexClient } from "./client"
export { loadTcgDexConfig, DEFAULT_TCGDEX_CONFIG } from "./config"
export { TCGDEX_ERROR_CODE, TcgDexError } from "./errors"
export { mapTcgDexLanguage } from "./language"
export { matchTcgdexCard, matchesLocalIdentity } from "./matching"
export type { TcgDexLookupDependency } from "./matching"
export { normalizeTcgdexCard, normalizeTcgdexRarity } from "./normalization"
export { TCGDEX_MATCH_CODE, TCGDEX_MATCH_SOURCE } from "./matching-types"
export { PROTECTED_ENRICHMENT_FIELDS } from "./enrichment"
export { candidateTcgdexSetIds } from "./suggest-set-mapping"
export type { TcgDexConfig } from "./config"
export type { TcgDexCard, TcgDexLanguage, TcgDexSetSummary } from "./types"
export type { CardEnrichmentData, NormalizedCardVariants, NormalizedRarityCandidate, TcgDexMatchInput, TcgDexMatchResult, TcgDexSetIdentity } from "./matching-types"
export type { EnrichmentProposal, ProtectedCommercialFields, ProtectedEnrichmentField } from "./enrichment"
