import { RARITY, RARITY_ICON_KEY, type Rarity, type RarityIconKey } from "../types"

const ICONS: Record<Rarity, RarityIconKey> = {
  [RARITY.ACE_SPEC]: RARITY_ICON_KEY.ACE_SPEC,
  [RARITY.BLACK_WHITE_RARE]: RARITY_ICON_KEY.BLACK_WHITE_RARE,
  [RARITY.COMMON]: RARITY_ICON_KEY.COMMON,
  [RARITY.DOUBLE_RARE]: RARITY_ICON_KEY.DOUBLE_RARE,
  [RARITY.HYPER_RARE]: RARITY_ICON_KEY.HYPER_RARE,
  [RARITY.ILLUSTRATION_RARE]: RARITY_ICON_KEY.ILLUSTRATION_RARE,
  [RARITY.MEGA_ATTACK_RARE]: RARITY_ICON_KEY.MEGA_ATTACK_RARE,
  [RARITY.MEGA_HYPER_RARE]: RARITY_ICON_KEY.MEGA_HYPER_RARE,
  [RARITY.NO_RARITY]: RARITY_ICON_KEY.NO_RARITY,
  [RARITY.PROMO]: RARITY_ICON_KEY.PROMO,
  [RARITY.SHINY_ULTRA_RARE]: RARITY_ICON_KEY.SHINY_ULTRA_RARE,
  [RARITY.ULTRA_RARE_SINGLE]: RARITY_ICON_KEY.ULTRA_RARE_SINGLE,
  [RARITY.ULTRA_RARE]: RARITY_ICON_KEY.ULTRA_RARE,
  [RARITY.UNCOMMON]: RARITY_ICON_KEY.UNCOMMON,
}

export function iconKeyForRarity(rarity: Rarity): RarityIconKey { return ICONS[rarity] }
