export interface PrepareSubscriptionInput {
  firstName: string
  email: string
  consentTextVersion: string
  /** Server-generated by default; override only for deterministic tests. */
  consentedAt?: Date
  source: string
  /** Override only for deterministic tests — see lifecycle/config.ts. */
  confirmationTokenTtlMinutesOverride?: number
}

/**
 * Internal-only outcomes for the future public subscribe route. The route
 * must still map every outcome to one generic public response — these
 * names exist so the caller that sends the confirmation email knows
 * whether a confirmation token was actually (re)issued.
 */
export type SignupResult =
  | { outcome: "PENDING_CREATED"; subscriberId: string; confirmationToken: string }
  | { outcome: "PENDING_REFRESHED"; subscriberId: string; confirmationToken: string }
  | { outcome: "ALREADY_CONFIRMED"; subscriberId: string }

export type ConfirmationResult =
  | { outcome: "CONFIRMED"; subscriberId: string; unsubscribeToken: string }
  | { outcome: "ALREADY_CONFIRMED" }
  | { outcome: "INVALID_OR_EXPIRED" }

export type UnsubscribeResult =
  | { outcome: "UNSUBSCRIBED" }
  | { outcome: "ALREADY_UNSUBSCRIBED" }
  | { outcome: "INVALID" }
