export interface PrepareSubscriptionInput {
  firstName: string
  email: string
  consentTextVersion: string
  /** Server-generated by default; override only for deterministic tests. */
  consentedAt?: Date
  source: string
  /** Override only for deterministic tests — see lifecycle/config.ts. */
  confirmationTokenTtlMinutesOverride?: number
}

/**
 * Internal-only outcomes for the future public subscribe route. The route
 * must still map every outcome to one generic public response — these
 * names exist so the caller that sends the confirmation email knows
 * whether a confirmation token was actually (re)issued.
 */
export type SignupResult =
  | { outcome: "PENDING_CREATED"; subscriberId: string; confirmationToken: string }
  | { outcome: "PENDING_REFRESHED"; subscriberId: string; confirmationToken: string }
  | { outcome: "ALREADY_CONFIRMED"; subscriberId: string }

export type ConfirmationResult =
  | { outcome: "CONFIRMED"; subscriberId: string; unsubscribeToken: string }
  | { outcome: "ALREADY_CONFIRMED" }
  | { outcome: "INVALID_OR_EXPIRED" }

export type UnsubscribeResult =
  | { outcome: "UNSUBSCRIBED" }
  | { outcome: "ALREADY_UNSUBSCRIBED" }
  | { outcome: "INVALID" }

/**
 * Outcome of attempting to reserve the next confirmation-email send
 * (Stage 2C.5). A reservation only succeeds when the subscriber is still
 * `PENDING`, the given confirmation-token hash is still the active one (a
 * later rotation supersedes it), the resend cooldown has elapsed, and no
 * other reservation is currently in flight (or the previous reservation is
 * stale). See `NewsletterModuleService.reserveConfirmationEmailSend` and
 * `docs/decisions/0005-newsletter-backend-design.md`.
 */
export type ConfirmationEmailReservationOutcome =
  | { reserved: true }
  | {
      reserved: false
      reason: "NOT_PENDING" | "STALE_TOKEN" | "SUPPRESSED_COOLDOWN" | "ALREADY_IN_FLIGHT"
    }
