import { SPECIAL_TREATMENT, type SpecialTreatment } from "../types"

const TREATMENTS: Record<string, SpecialTreatment> = {
  "ENERGY REVERSE HOLO": SPECIAL_TREATMENT.ENERGY_REVERSE,
  "POKÉ BALL REVERSE HOLO": SPECIAL_TREATMENT.POKE_BALL_REVERSE,
  "POKE BALL REVERSE HOLO": SPECIAL_TREATMENT.POKE_BALL_REVERSE,
  "MASTER BALL REVERSE HOLO": SPECIAL_TREATMENT.MASTER_BALL_REVERSE,
  "LOVE BALL REVERSE HOLO": SPECIAL_TREATMENT.LOVE_BALL_REVERSE,
  "QUICK BALL REVERSE HOLO": SPECIAL_TREATMENT.QUICK_BALL_REVERSE,
  "FRIEND BALL REVERSE HOLO": SPECIAL_TREATMENT.FRIEND_BALL_REVERSE,
  "DUSK BALL REVERSE HOLO": SPECIAL_TREATMENT.DUSK_BALL_REVERSE,
  "ROCKET REVERSE HOLO": SPECIAL_TREATMENT.ROCKET_REVERSE,
  "POKÉ BALL": SPECIAL_TREATMENT.POKE_BALL,
  "POKE BALL": SPECIAL_TREATMENT.POKE_BALL,
  "MASTER BALL": SPECIAL_TREATMENT.MASTER_BALL,
  "STARLIGHT HOLO": SPECIAL_TREATMENT.STARLIGHT_HOLO,
  "COSMOS HOLO": SPECIAL_TREATMENT.COSMOS_HOLO,
  "GALAXY HOLO": SPECIAL_TREATMENT.GALAXY_HOLO,
  "CRACKED ICE": SPECIAL_TREATMENT.CRACKED_ICE,
  STAMPED: SPECIAL_TREATMENT.STAMPED,
  "PRERELEASE STAMPED": SPECIAL_TREATMENT.PRERELEASE_STAMPED,
  "PROMOTIONAL STAMPED": SPECIAL_TREATMENT.PROMOTIONAL_STAMPED,
  TEXTURED: SPECIAL_TREATMENT.TEXTURED,
  ETCHED: SPECIAL_TREATMENT.ETCHED,
}

export interface TreatmentResolution { specialTreatment: SpecialTreatment; confirmed: boolean }

export function resolveSpecialTreatment(raw?: string | null): TreatmentResolution {
  if (!raw?.trim()) return { specialTreatment: SPECIAL_TREATMENT.NONE, confirmed: true }
  const value = raw.normalize("NFC").trim().toUpperCase()
  const treatment = TREATMENTS[value]
  if (treatment) return { specialTreatment: treatment, confirmed: true }
  if (["NORMAL", "NON-FOIL", "NON FOIL", "REGULAR", "HOLO", "REVERSE HOLO"].includes(value)) {
    return { specialTreatment: SPECIAL_TREATMENT.NONE, confirmed: true }
  }
  return { specialTreatment: SPECIAL_TREATMENT.OTHER, confirmed: false }
}
